### ISSUE TITLE
Web designer (front end 2)

### ISSUE THREAD

**Issue by webdv1pr** [near/openweb-jobs#1]
- [__Project__](http://127.0.0.1:5555/profile/1)
- __Type__: `project` `freelance`
- __Category__: `frontend` `design`
- __Location__: `cyprus:polis`
- __Remote__: `yes`
- __Required skills__: `html` `css` `meteorjs` `nodejs`
- [__View this job post__](http://127.0.0.1:5555/job/1)

We are looking for experienced web designer and front-end developer.
Please apply if you think you are good fit 👨‍💻

**Comment by dr-dimitru** [comment]
Hello!

I'm interested in this position, please take a look at [my profile](http://127.0.0.1:5555/profile/4) and my GitHub account @dr-dimitru
I might help you to solve this
